apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  labels:
    component: minio
stringData:
  cloud: |
    [default]
    aws_access_key_id = <mini-user>
    aws_secret_access_key = <minio-password>
